In [3]:
import pandas as pd
import numpy as np
import sodapy
from sodapy import Socrata
from requests.adapters import HTTPAdapter
from urllib3.util import Retry

In [4]:
client = Socrata("datacatalog.cookcountyil.gov", 
                 "Q6WYPYmE8Ff40YoqUQJvDXJSR", 
                 timeout=60)

meta = []
meta = client.get_metadata("cjeq-bs86")

In [5]:
meta

{'id': 'cjeq-bs86',
 'name': 'Medical Examiner Case Archive',
 'assetType': 'dataset',
 'attribution': 'Cook County Medical Examiner',
 'attributionLink': 'https://www.cookcountyil.gov/agency/medical-examiner',
 'averageRating': 0,
 'category': 'Health & Human Services',
 'createdAt': 1515026009,
 'description': 'Effective April 1, 2022, the Cook County Medical Examiner’s Office no longer takes jurisdiction over hospital, nursing home or hospice COVID-19 deaths unless there is another factor that falls within the Office’s jurisdiction. Data continues to be collected for COVID-19 deaths in Cook County on the Illinois Dept. of Public Health COVID-19 dashboard (https://dph.illinois.gov/covid19/data.html).\n\nThis contains information about deaths that occurred in Cook County that were under the Medical Examiner’s jurisdiction. Not all deaths that occur in Cook County are reported to the Medical Examiner or fall under the jurisdiction of the Medical Examiner. The Medical Examiner’s Office determines cause and manner of death for those cases that fall under its jurisdiction. Cause of death describes the reason the person died. This dataset includes information from deaths starting in August 2014 to the present, with information updated daily.\n\nChanges:\nDecember 16, 2022: The Cook County Commissioner District field now reflects the boundaries that went into effect December 5, 2022.\n\nSeptember 8, 2023: The Primary Cause field is now a combination of the Primary Cause Line A, Line B, and Line C fields.\n\nJune 4, 2026: There are 3 new fields: Transportation Related, Transportation Related Vehicle Type, and Transportation Related Decedent Status',
 'diciBackend': False,
 'displayType': 'table',
 'downloadCount': 50638,
 'hideFromCatalog': False,
 'hideFromDataJson': False,
 'licenseId': 'PUBLIC_DOMAIN',
 'locale': 'en_US',
 'locked': False,
 'newBackend': True,
 'numberOfComments': 0,
 'oid': 42195550,
 'provenance': 'official',
 'publicationAppendEnabled': False,
 'publicationDate': 1780583561,
 'publicationGroup': 14762146,
 'publicationStage': 'published',
 'rowIdentifierColumnId': 634670904,
 'rowsUpdatedAt': 1785617657,
 'rowsUpdatedBy': 'mngp-xcc5',
 'tableId': 20411157,
 'totalTimesRated': 0,
 'viewCount': 701586,
 'viewLastModified': 1785617595,
 'viewType': 'tabular',
 'approvals': [{'reviewedAt': 1541608004,
   'reviewedAutomatically': True,
   'state': 'approved',
   'submissionId': 7512342,
   'submissionObject': 'public_audience_request',
   'submissionOutcome': 'change_audience',
   'submittedAt': 1541608004,
   'targetAudience': 'public',
   'workflowId': 2031,
   'submissionDetails': {'permissionType': 'READ'},
   'submissionOutcomeApplication': {'failureCount': 0, 'status': 'success'},
   'submitter': {'id': 'u38g-hbsa', 'displayName': 'Cook County Open Data'}}],
 'clientContext': {'clientContextVariables': [], 'inheritedVariables': {}},
 'columns': [{'id': 634670904,
   'name': 'Case Number',
   'dataTypeName': 'text',
   'description': "Case Number assigned by the Medical Examiner's office.",
   'fieldName': 'casenumber',
   'position': 1,
   'renderTypeName': 'text',
   'tableColumnId': 59276118,
   'width': 168,
   'cachedContents': {'non_null': '97793',
    'largest': 'ME2026-04085',
    'null': '0',
    'top': [{'item': 'ME2020-02311', 'count': '1'},
     {'item': 'ME2022-08246', 'count': '1'},
     {'item': 'ME2020-00469', 'count': '1'},
     {'item': 'ME2024-04396', 'count': '1'},
     {'item': 'ME2022-01982', 'count': '1'},
     {'item': 'ME2021-11957', 'count': '1'},
     {'item': 'ME2017-05605', 'count': '1'},
     {'item': 'ME2016-04299', 'count': '1'},
     {'item': 'ME2026-03283', 'count': '1'},
     {'item': 'ME2016-02016', 'count': '1'},
     {'item': 'ME2026-00882', 'count': '1'},
     {'item': 'ME2026-01492', 'count': '1'},
     {'item': 'ME2019-01485', 'count': '1'},
     {'item': 'ME2023-05176', 'count': '1'},
     {'item': 'ME2022-03792', 'count': '1'},
     {'item': 'ME2026-03129', 'count': '1'},
     {'item': 'ME2020-04390', 'count': '1'},
     {'item': 'ME2020-05438', 'count': '1'},
     {'item': 'ME2025-05655', 'count': '1'},
     {'item': 'ME2016-00029', 'count': '1'}],
    'smallest': 'ME2014-00001',
    'count': '97793',
    'cardinality': '97793'},
   'format': {'align': 'left'}},
  {'id': 634670905,
   'name': 'Date of Incident',
   'dataTypeName': 'calendar_date',
   'description': 'Date incident occurred',
   'fieldName': 'incident_date',
   'position': 2,
   'renderTypeName': 'calendar_date',
   'tableColumnId': 59276119,
   'width': 184,
   'cachedContents': {'non_null': '95516',
    'largest': '9999-09-09T00:00:00.000',
    'null': '2277',
    'top': [{'item': '2022-01-11T00:00:00.000', 'count': '36'},
     {'item': '2020-05-04T00:00:00.000', 'count': '34'},
     {'item': '2020-04-16T00:00:00.000', 'count': '34'},
     {'item': '2020-04-29T00:00:00.000', 'count': '33'},
     {'item': '2020-05-05T00:00:00.000', 'count': '32'},
     {'item': '2020-04-24T00:00:00.000', 'count': '32'},
     {'item': '2020-04-19T00:00:00.000', 'count': '32'},
     {'item': '2020-04-20T00:00:00.000', 'count': '32'},
     {'item': '2020-04-23T00:00:00.000', 'count': '30'},
     {'item': '2022-01-03T00:00:00.000', 'count': '29'},
     {'item': '2021-12-30T00:00:00.000', 'count': '29'},
     {'item': '2020-12-14T00:00:00.000', 'count': '29'},
     {'item': '2020-04-28T00:00:00.000', 'count': '28'},
     {'item': '2020-11-13T00:00:00.000', 'count': '28'},
     {'item': '2020-11-10T00:00:00.000', 'count': '27'},
     {'item': '2020-04-18T00:00:00.000', 'count': '27'},
     {'item': '2020-04-22T00:00:00.000', 'count': '27'},
     {'item': '2020-04-12T00:00:00.000', 'count': '26'},
     {'item': '2020-04-30T00:00:00.000', 'count': '26'},
     {'item': '2020-12-02T00:00:00.000', 'count': '26'}],
    'smallest': '1948-05-25T04:00:00.000',
    'count': '97793',
    'cardinality': '97793'},
   'format': {'view': 'date_time', 'align': 'left'}},
  {'id': 634670906,
   'name': 'Date of Death',
   'dataTypeName': 'calendar_date',
   'description': 'Date the deceased was pronounced dead',
   'fieldName': 'death_date',
   'position': 3,
   'renderTypeName': 'calendar_date',
   'tableColumnId': 59276120,
   'width': 165,
   'cachedContents': {'non_null': '97718',
    'largest': '2027-04-17T17:50:00.000',
    'null': '75',
    'top': [{'item': '2018-08-26T04:09:00.000', 'count': '7'},
     {'item': '2016-02-04T13:53:00.000', 'count': '6'},
     {'item': '2019-04-19T10:45:00.000', 'count': '5'},
     {'item': '2017-03-30T16:32:00.000', 'count': '4'},
     {'item': '2022-01-18T14:15:00.000', 'count': '4'},
     {'item': '2024-01-21T11:36:00.000', 'count': '4'},
     {'item': '2022-03-09T02:22:00.000', 'count': '4'},
     {'item': '2020-05-07T23:00:00.000', 'count': '3'},
     {'item': '2020-05-23T03:10:00.000', 'count': '3'},
     {'item': '2024-01-29T23:24:00.000', 'count': '3'},
     {'item': '2020-05-14T11:50:00.000', 'count': '3'},
     {'item': '2019-02-17T01:30:00.000', 'count': '3'},
     {'item': '2022-01-12T07:57:00.000', 'count': '3'},
     {'item': '2015-10-30T17:34:00.000', 'count': '3'},
     {'item': '2025-11-02T01:34:00.000', 'count': '3'},
     {'item': '2020-12-22T04:15:00.000', 'count': '3'},
     {'item': '2016-10-03T23:50:00.000', 'count': '3'},
     {'item': '2020-12-19T20:20:00.000', 'count': '3'},
     {'item': '2020-05-10T22:24:00.000', 'count': '3'},
     {'item': '2020-12-10T14:50:00.000', 'count': '3'}],
    'smallest': '2008-09-11T06:00:00.000',
    'count': '97793',
    'cardinality': '97793'},
   'format': {'view': 'date_time', 'align': 'left'}},
  {'id': 634670907,
   'name': 'Age',
   'dataTypeName': 'number',
   'description': 'Age of decedent',
   'fieldName': 'age',
   'position': 4,
   'renderTypeName': 'number',
   'tableColumnId': 59276121,
   'width': 105,
   'cachedContents': {'non_null': '97325',
    'largest': '109',
    'null': '468',
    'top': [{'item': '59', 'count': '2038'},
     {'item': '58', 'count': '1994'},
     {'item': '62', 'count': '1989'},
     {'item': '61', 'count': '1962'},
     {'item': '64', 'count': '1953'},
     {'item': '60', 'count': '1950'},
     {'item': '63', 'count': '1929'},
     {'item': '65', 'count': '1923'},
     {'item': '57', 'count': '1857'},
     {'item': '56', 'count': '1835'},
     {'item': '67', 'count': '1783'},
     {'item': '68', 'count': '1739'},
     {'item': '66', 'count': '1739'},
     {'item': '54', 'count': '1716'},
     {'item': '55', 'count': '1697'},
     {'item': '70', 'count': '1566'},
     {'item': '69', 'count': '1564'},
     {'item': '53', 'count': '1554'},
     {'item': '52', 'count': '1485'},
     {'item': '51', 'count': '1453'}],
    'smallest': '0',
    'count': '97793',
    'cardinality': '97793'},
   'format': {'precisionStyle': 'standard', 'align': 'right'}},
  {'id': 634670908,
   'name': 'Gender',
   'dataTypeName': 'text',
   'description': 'Gender of decedent',
   'fieldName': 'gender',
   'position': 5,
   'renderTypeName': 'text',
   'tableColumnId': 59276122,
   'width': 134,
   'cachedContents': {'non_null': '97478',
    'largest': 'Unknown',
    'null': '315',
    'top': [{'item': 'Male', 'count': '68005'},
     {'item': 'Female', 'count': '29414'},
     {'item': 'Unknown', 'count': '59'}],
    'smallest': 'Female',
    'count': '97793',
    'cardinality': '97793'},
   'format': {'align': 'left'}},
  {'id': 634670909,
   'name': 'Race',
   'dataTypeName': 'text',
   'description': 'Race of decedent',
   'fieldName': 'race',
   'position': 6,
   'renderTypeName': 'text',
   'tableColumnId': 59276123,
   'width': 114,
   'cachedContents': {'non_null': '97280',
    'largest': 'White',
    'null': '513',
    'top': [{'item': 'White', 'count': '52769'},
     {'item': 'Black', 'count': '40538'},
     {'item': 'Asian', 'count': '2352'},
     {'item': 'Other', 'count': '1154'},
     {'item': 'Unknown', 'count': '388'},
     {'item': 'Am. Indian', 'count': '79'}],
    'smallest': 'Am. Indian',
    'count': '97793',
    'cardinality': '97793'},
   'format': {'align': 'left'}},
  {'id': 634670910,
   'name': 'Latino',
   'dataTypeName': 'checkbox',
   'description': 'Whether the family of the decedent identified him/her as Latino',
   'fieldName': 'latino',
   'position': 7,
   'renderTypeName': 'checkbox',
   'tableColumnId': 59276124,
   'width': 80,
   'cachedContents': {'non_null': '97793',
    'null': '0',
    'top': [{'item': False, 'count': '84696'},
     {'item': True, 'count': '13097'}],
    'count': '97793',
    'cardinality': '97793'},
   'format': {'align': 'left'}},
  {'id': 634670911,
   'name': 'Manner of Death',
   'dataTypeName': 'text',
   'description': 'One of five categories: Homicide, Suicide, Natural, Accident, Undetermined',
   'fieldName': 'manner',
   'position': 8,
   'renderTypeName': 'text',
   'tableColumnId': 59276125,
   'width': 129,
   'cachedContents': {'non_null': '97192',
    'largest': 'UNDETERMINED',
    'null': '601',
    'top': [{'item': 'NATURAL', 'count': '46786'},
     {'item': 'ACCIDENT', 'count': '32628'},
     {'item': 'HOMICIDE', 'count': '9614'},
     {'item': 'SUICIDE', 'count': '5708'},
     {'item': 'UNDETERMINED', 'count': '1835'},
     {'item': 'PENDING', 'count': '621'}],
    'smallest': 'ACCIDENT',
    'count': '97793',
    'cardinality': '97793'},
   'format': {'align': 'left'}},
  {'id': 634670912,
   'name': 'Primary Cause',
   'dataTypeName': 'text',
   'description': 'Primary reason the person died. This field combines Primary Cause Line A, Line B, and Line C into one field',
   'fieldName': 'primarycause',
   'position': 9,
   'renderTypeName': 'text',
   'tableColumnId': 59276126,
   'width': 357,
   'cachedContents': {'non_null': '97120',
    'largest': 'ZOLPIDEM TOXICITY',
    'null': '673',
    'top': [{'item': 'ORGANIC CARDIOVASCULAR DISEASE', 'count': '11943'},
     {'item': 'MULTIPLE GUNSHOT WOUNDS', 'count': '4880'},
     {'item': 'PNEUMONIA. NOVEL CORONA (COVID-19) VIRAL INFECTION',
      'count': '4101'},
     {'item': 'HYPERTENSIVE CARDIOVASCULAR DISEASE', 'count': '4012'},
     {'item': 'NOVEL CORONA (COVID-19) VIRAL INFECTION', 'count': '2549'},
     {'item': 'HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE',
      'count': '1840'},
     {'item': 'CHRONIC ETHANOLISM', 'count': '1563'},
     {'item': 'ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE', 'count': '1384'},
     {'item': 'HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULAR DISEASE',
      'count': '1336'},
     {'item': 'GUNSHOT WOUND OF HEAD', 'count': '1209'},
     {'item': 'HANGING', 'count': '1207'},
     {'item': 'PNEUMONIA. NOVEL CORONA (COVID-19) VIRUS INFECTION',
      'count': '957'},
     {'item': 'UNDETERMINED', 'count': '903'},
     {'item': 'HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE',
      'count': '805'},
     {'item': 'ACUTE HYPOXIC RESPIRATORY FAILURE. PNEUMONIA. NOVEL CORONA (COVID-19) VIRAL INFECTION',
      'count': '756'},
     {'item': 'DROWNING', 'count': '634'},
     {'item': 'NOVEL CORONA (COVID-19) VIRUS INFECTION', 'count': '627'},
     {'item': 'COCAINE TOXICITY', 'count': '602'},
     {'item': 'ACUTE RESPIRATORY FAILURE WITH HYPOXIA. PNEUMONIA. NOVEL CORONA (COVID-19) VIRAL INFECTION',
      'count': '572'},
     {'item': 'COMPLICATIONS OF NOVEL CORONA (COVID-19) VIRAL INFECTION',
      'count': '534'}],
    'smallest': '.',
    'count': '97793',
    'cardinality': '97793'},
   'format': {'align': 'right'}},
  {'id': 634670913,
   'name': 'Primary Cause Line A',
   'dataTypeName': 'text',
   'description': 'Primary reason the person died',
   'fieldName': 'primarycause_linea',
   'position': 10,
   'renderTypeName': 'text',
   'tableColumnId': 97324405,
   'width': 316,
   'cachedContents': {'non_null': '97120',
    'largest': 'ZOLPIDEM TOXICITY',
    'null': '673',
    'top': [{'item': 'ORGANIC CARDIOVASCULAR DISEASE', 'count': '11997'},
     {'item': 'PNEUMONIA', 'count': '5187'},
     {'item': 'MULTIPLE GUNSHOT WOUNDS', 'count': '4883'},
     {'item': 'HYPERTENSIVE CARDIOVASCULAR DISEASE', 'count': '4039'},
     {'item': 'MULTIPLE INJURIES', 'count': '3696'},
     {'item': 'NOVEL CORONA (COVID-19) VIRAL INFECTION', 'count': '2556'},
     {'item': 'ACUTE HYPOXIC RESPIRATORY FAILURE', 'count': '1847'},
     {'item': 'HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE',
      'count': '1846'},
     {'item': 'CHRONIC ETHANOLISM', 'count': '1567'},
     {'item': 'ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE', 'count': '1390'},
     {'item': 'HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULAR DISEASE',
      'count': '1339'},
     {'item': 'GUNSHOT WOUND OF HEAD', 'count': '1210'},
     {'item': 'HANGING', 'count': '1209'},
     {'item': 'MULTIPLE BLUNT FORCE INJURIES', 'count': '1135'},
     {'item': 'UNDETERMINED', 'count': '908'},
     {'item': 'ACUTE RESPIRATORY FAILURE WITH HYPOXIA', 'count': '890'},
     {'item': 'HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE',
      'count': '808'},
     {'item': 'COMPLICATIONS OF MULTIPLE INJURIES', 'count': '766'},
     {'item': 'DROWNING', 'count': '709'},
     {'item': 'NOVEL CORONA (COVID-19) VIRUS INFECTION', 'count': '627'}],
    'smallest': '.',
    'count': '97793',
    'cardinality': '97793'},
   'format': {}},
  {'id': 634670914,
   'name': 'Primary Cause Line B',
   'dataTypeName': 'text',
   'description': 'Primary reason the person died',
   'fieldName': 'primarycause_lineb',
   'position': 11,
   'renderTypeName': 'text',
   'tableColumnId': 59276127,
   'width': 316,
   'cachedContents': {'non_null': '29311',
    'largest': 'ZOPICLONE, FLUOXETINE, FENTANYL, ACETYL FENTANYL, MITRAGYNINE, AND HEROIN) TOXICITY',
    'null': '68482',
    'top': [{'item': 'NOVEL CORONA (COVID-19) VIRAL INFECTION',
      'count': '5932'},
     {'item': 'FALL', 'count': '3236'},
     {'item': 'PNEUMONIA', 'count': '2404'},
     {'item': 'NOVEL CORONA (COVID-19) VIRUS INFECTION', 'count': '1874'},
     {'item': 'MOTOR VEHICLE COLLISION', 'count': '1127'},
     {'item': 'MOTOR VEHICLE STRIKING PEDESTRIAN', 'count': '664'},
     {'item': 'HANGING', 'count': '543'},
     {'item': 'MOTOR VEHICLE CRASH', 'count': '417'},
     {'item': 'MOTOR VEHICLE STRIKING FIXED OBJECT', 'count': '367'},
     {'item': 'FALL DOWN STAIRS', 'count': '366'},
     {'item': 'FALL FROM HEIGHT', 'count': '353'},
     {'item': 'PROBABLE FALL', 'count': '335'},
     {'item': 'ASSAULT', 'count': '310'},
     {'item': 'HYPERTENSIVE CARDIOVASCULAR DISEASE', 'count': '266'},
     {'item': 'UNWITNESSED FALL', 'count': '245'},
     {'item': 'PEDESTRIAN STRUCK BY MOTOR VEHICLE', 'count': '244'},
     {'item': 'CHOKING ON FOOD BOLUS', 'count': '237'},
     {'item': 'TRAIN STRIKING PEDESTRIAN', 'count': '227'},
     {'item': 'FALL(S)', 'count': '227'},
     {'item': 'HOUSE FIRE', 'count': '203'}],
    'smallest': '.',
    'count': '97793',
    'cardinality': '97793'},
   'format': {'align': 'right'}},
  {'id': 634670915,
   'name': 'Primary Cause Line C',
   'dataTypeName': 'text',
   'description': 'Primary reason the person died',
   'fieldName': 'primarycause_linec',
   'position': 12,
   'renderTypeName': 'text',
   'tableColumnId': 59276128,
   'width': 316,
   'cachedContents': {'non_null': '3554',
    'largest': 'WORKING ON PUTTING OUT AN INCENDIARY RESIDENTIAL FIRE',
    'null': '94239',
    'top': [{'item': 'NOVEL CORONA (COVID-19) VIRAL INFECTION',
      'count': '2059'},
     {'item': 'NOVEL CORONA (COVID-19) VIRUS INFECTION', 'count': '381'},
     {'item': 'HYPERTENSIVE CARDIOVASCULAR DISEASE', 'count': '91'},
     {'item': 'HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULAR DISEASE',
      'count': '66'},
     {'item': 'HOUSE FIRE', 'count': '56'},
     {'item': 'FALL', 'count': '45'},
     {'item': '.', 'count': '42'},
     {'item': 'CHRONIC ETHANOLISM', 'count': '36'},
     {'item': 'CARELESS USE OF SMOKING MATERIALS', 'count': '22'},
     {'item': 'APARTMENT FIRE', 'count': '20'},
     {'item': 'FOOD BOLUS', 'count': '16'},
     {'item': 'PLASTIC BAG OVER HEAD CONNECTED TO HELIUM TANK', 'count': '14'},
     {'item': 'HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE',
      'count': '12'},
     {'item': 'ATHEROSCLEROTIC CARDIOVASCULAR DISEASE', 'count': '12'},
     {'item': 'PLASTIC BAG OVER HEAD', 'count': '11'},
     {'item': 'MOTOR VEHICLE COLLISION', 'count': '10'},
     {'item': 'ASSAULT', 'count': '9'},
     {'item': 'HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE',
      'count': '8'},
     {'item': 'ATHEROSCLEROTIC AND HYPERTENSIVE CARDIOVASCULAR DISEASE',
      'count': '8'},
     {'item': 'CHRONIC ALCOHOLISM', 'count': '7'}],
    'smallest': '.',
    'count': '97793',
    'cardinality': '97793'},
   'format': {'align': 'right'}},
  {'id': 634670916,
   'name': 'Secondary Cause',
   'dataTypeName': 'text',
   'description': 'Secondary reason',
   'fieldName': 'secondarycause',
   'position': 13,
   'renderTypeName': 'text',
   'tableColumnId': 59276129,
   'width': 433,
   'cachedContents': {'non_null': '36700',
    'largest': 'YPERTENSION, DEMENTIA, HYPERLIPEDMIA',
    'null': '61093',
    'top': [{'item': 'DIABETES MELLITUS', 'count': '2461'},
     {'item': 'OBESITY', 'count': '2186'},
     {'item': 'CHRONIC ETHANOLISM', 'count': '1298'},
     {'item': 'HYPERTENSION', 'count': '1171'},
     {'item': 'HYPERTENSIVE CARDIOVASCULAR DISEASE', 'count': '825'},
     {'item': 'CHRONIC OBSTRUCTIVE PULMONARY DISEASE', 'count': '571'},
     {'item': 'HYPERTENSION, DIABETES MELLITUS', 'count': '489'},
     {'item': 'HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE',
      'count': '465'},
     {'item': 'HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULAR DISEASE',
      'count': '339'},
     {'item': 'DIABETES MELLITUS, OBESITY', 'count': '323'},
     {'item': 'CHRONIC SUBSTANCE ABUSE', 'count': '308'},
     {'item': 'MORBID OBESITY', 'count': '260'},
     {'item': 'DEMENTIA', 'count': '251'},
     {'item': 'DIABETES MELLITUS, HYPERTENSION', 'count': '248'},

In [6]:
testy = client.get("cjeq-bs86", where="heat_related = True", exclude_system_fields=False)
df = pd.DataFrame(testy)

In [7]:
print(len(df))

58

In [8]:
df.head()

,casenumber,incident_date,death_date,age,gender,race,latino,manner,primarycause,primarycause_linea,...,residence_city,residence_zip,objectid,chi_ward,chi_commarea,covid_related,:id,:created_at,:updated_at,primarycause_lineb
0,ME2016-03171,2016-06-27T15:24:00.000,2016-06-27T16:36:00.000,83,Female,Black,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,Chicago,60629,2739,9.0,ROSELAND,False,row-cjgt_crd7-xyuy,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN
1,ME2017-04963,2017-10-22T04:56:00.000,2017-10-22T05:55:00.000,61,Male,Black,False,ACCIDENT,HYPERTHERMIA. EXPOSURE TO HIGH ENVIRONMENTAL T...,HYPERTHERMIA,...,Richton Park,60471,4762,NaN,NaN,False,row-anqg-rrnp-nc7f,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,EXPOSURE TO HIGH ENVIRONMENTAL TEMPERATURE
2,ME2017-04962,2017-10-22T08:50:00.000,2017-10-22T09:28:00.000,44,Male,Black,False,ACCIDENT,HYPERTHERMIA . EXPOSURE TO HIGH ENVIRONMENTAL ...,HYPERTHERMIA,...,Glenwood,60425,4767,NaN,NaN,False,row-zkkj-326b.5nki,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,EXPOSURE TO HIGH ENVIRONMENTAL TEMPERATURE
3,ME2019-02763,2019-06-17T15:00:00.000,2019-06-17T15:55:00.000,76,Male,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE. FAULTY MODIFICATI...,ENVIRONMENTAL HEAT EXPOSURE,...,Country Club Hills,60478,10926,NaN,NaN,False,row-bdwb~ncpq_653d,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,FAULTY MODIFICATION OF HOME FURNACE AND THERMO...
4,ME2015-03061,2015-07-19T01:00:00.000,2015-07-19T01:40:00.000,70,Female,White,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,HYPERTENSIVE CARDIOVASCULAR DISEASE,...,Brookfield,60513,11090,NaN,NaN,False,row-u2wg.si6s.22un,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN

In [9]:
# Source - https://stackoverflow.com/a/32490661
# Posted by diegueus9, modified by community. See post 'Timeline' for change history
# Retrieved 2026-07-30, License - CC BY-SA 4.0

from datetime import datetime, timedelta

In [10]:
# rightnow = datetime.today().strftime('%Y-%m-%d %H:%M:%S')
rightnow = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
print(rightnow)

2026-08-01 22:04:42

In [11]:
today = datetime.today().strftime('%Y-%m-%d')
print(today)

2026-08-01

In [12]:
yesterday = datetime.today() - timedelta(1)
yesterday = yesterday.strftime('%Y-%m-%d')
print(yesterday)

2026-07-31

In [13]:
# query = """
#     SELECT * 
#     WHERE 
#         death_date BETWEEN '2026-01-01' AND '2026-08-01'
#         AND heat_related = 'true'
# """


today_query = f"SELECT * WHERE heat_related = 'true' AND death_date BETWEEN '2026-01-01' AND '{today}'"

# query = """
#     SELECT * 
#     WHERE 
#         death_date BETWEEN '2026-01-01' AND today
#         AND heat_related = 'true'
# """

today_download = client.get("cjeq-bs86", query=today_query, exclude_system_fields=False)
df2 = pd.DataFrame(today_download)

In [14]:
df2.head()

,casenumber,incident_date,death_date,age,gender,race,latino,manner,primarycause,primarycause_linea,...,residence_city,residence_zip,objectid,covid_related,:id,:created_at,:updated_at,primarycause_lineb,chi_ward,chi_commarea
0,ME2026-03456,2026-07-01T13:09:00.000,2026-07-01T12:32:00.000,69,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,ORGANIC CARDIOVASCULAR DISEASE,...,Evanston,60202,97252,False,row-qr98-f75u.wfvp,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,NaN,NaN
1,ME2026-03475,2026-07-01T23:33:00.000,2026-07-01T20:31:00.000,46,Male,White,False,ACCIDENT,HYPERTHERMIA. ENVIRONMENTAL HEAT EXPOSURE IN T...,HYPERTHERMIA,...,Chicago,60620,97263,False,row-rzej~pb48-7b4c,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,ENVIRONMENTAL HEAT EXPOSURE IN THE SETTING OF ...,16.0,CHICAGO LAWN
2,ME2026-03491,2026-07-02T15:57:00.000,2026-07-02T15:32:00.000,48,Male,Black,False,ACCIDENT,HEAT STROKE,HEAT STROKE,...,Chicago,60612,97283,False,row-4agc.n45x.zqvw,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,28.0,EAST GARFIELD PARK
3,ME2026-03506,2026-07-03T10:18:00.000,2026-07-03T10:01:00.000,57,Male,White,True,NATURAL,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,...,Chicago,60608,97297,False,row-8b9p.nu4n~5fcf,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,12.0,MCKINLEY PARK
4,ME2026-03513,2026-07-03T17:48:00.000,2026-07-03T17:25:00.000,71,Female,Black,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,HYPERTENSIVE CARDIOVASCULAR DISEASE,...,Chicago,60621,97304,False,row-mt4y_zt3v_skr2,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,16.0,ENGLEWOOD

In [15]:
yesterday_query = f"SELECT * WHERE heat_related = 'true' AND death_date BETWEEN '2026-01-01' AND '{yesterday}'"

yesterday_download = client.get("cjeq-bs86", query=yesterday_query, exclude_system_fields=False)
df3 = pd.DataFrame(yesterday_download)

print(len(df3))

9

In [ ]:
# test = client.get_all("cjeq-bs86", content_type='csv')
# testdf = pd.DataFrame(test)
# testdf

KeyboardInterrupt:

In [ ]:
# # dataset
# data = "https://datacatalog.cookcountyil.gov/Health-Human-Services/Medical-Examiner-Case-Archive/cjeq-bs86/explore/query?SELECT%0A%20%20%60casenumber%60%2C%0A%20%20%60incident_date%60%2C%0A%20%20%60death_date%60%2C%0A%20%20%60age%60%2C%0A%20%20%60gender%60%2C%0A%20%20%60race%60%2C%0A%20%20%60latino%60%2C%0A%20%20%60manner%60%2C%0A%20%20%60primarycause%60%2C%0A%20%20%60primarycause_linea%60%2C%0A%20%20%60primarycause_lineb%60%2C%0A%20%20%60primarycause_linec%60%2C%0A%20%20%60secondarycause%60%2C%0A%20%20%60gunrelated%60%2C%0A%20%20%60opioids%60%2C%0A%20%20%60cold_related%60%2C%0A%20%20%60heat_related%60%2C%0A%20%20%60transportation_related%60%2C%0A%20%20%60commissioner_district%60%2C%0A%20%20%60incident_street%60%2C%0A%20%20%60incident_city%60%2C%0A%20%20%60incident_zip%60%2C%0A%20%20%60longitude%60%2C%0A%20%20%60latitude%60%2C%0A%20%20%60location%60%2C%0A%20%20%60residence_city%60%2C%0A%20%20%60residence_zip%60%2C%0A%20%20%60objectid%60%2C%0A%20%20%60chi_ward%60%2C%0A%20%20%60chi_commarea%60%2C%0A%20%20%60covid_related%60%2C%0A%20%20%60transportation_related_type%60%2C%0A%20%20%60transportation_status%60%0AWHERE%20%60heat_related%60%20IN%20%28%22true%22%29%0AORDER%20BY%20%60casenumber%60%20DESC%20NULL%20FIRST"
# test_df = pd.read_csv(data)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 21, saw 245

In [ ]:
test_df

In [19]:
df2.columns

Index(['casenumber', 'incident_date', 'death_date', 'age', 'gender', 'race',
       'latino', 'manner', 'primarycause', 'primarycause_linea',
       'secondarycause', 'gunrelated', 'opioids', 'cold_related',
       'heat_related', 'transportation_related', 'commissioner_district',
       'incident_street', 'incident_city', 'incident_zip', 'longitude',
       'latitude', 'location', 'residence_city', 'residence_zip', 'objectid',
       'covid_related', ':id', ':created_at', ':updated_at',
       'primarycause_lineb', 'chi_ward', 'chi_commarea'],
      dtype='str')

using this to try and figure out what to send to slack.

needs:
* case number
* incident date
* death date
* {age}-year-old {race} {gender}. (Latino? {latino})
* primarycause
* secondarycause
* concat: incident_street, city, zip
* chicommarea, chiward